image: docker:stable

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  NAME: imtlab/baseimage-node
  VERSION: "18.0.0"

services:
  - docker:dind

stages:
  - build
  - test
  - push

before_script:
  - apk add --update alpine-sdk bash

build-10.15.3:
  stage: build
  artifacts:
   paths:
    - build-10_15_3.tgz
   expire_in: 1 day
  script:
    - make build_node10153
    - docker save $NAME:10.15.3-$VERSION | gzip > build-10_15_3.tgz

test-all:
  stage: test
  script:
    - gunzip -c build-10_15_3.tgz | docker load 
    - make test
  dependencies:
    - build-10.15.3

push-all:
  stage: push
  only:
    - tags
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - gunzip -c build-10_15_3.tgz | docker load 
    - make release
  dependencies:
    - build-10.15.3
